INSERT INTO fragments (filename, tekst) VALUES ('frag_0.mp3', '[Dudley] Daddy!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_1.mp3', 'Eye of rabbit, harp string hum,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_2.mp3', 'turn this water into rum.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_3.mp3', 'Eye of rabbit, harp string hum...');
INSERT INTO fragments (filename, tekst) VALUES ('frag_4.mp3', 'What\'s Seamus trying to do');
INSERT INTO fragments (filename, tekst) VALUES ('frag_5.mp3', 'to that glass of water?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_6.mp3', 'Turn it to rum.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_7.mp3', 'Actually managed a weak tea yesterday,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_8.mp3', 'before he...');
INSERT INTO fragments (filename, tekst) VALUES ('frag_9.mp3', '[Harry] Up.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_10.mp3', 'Up!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_11.mp3', 'Up!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_12.mp3', 'Shut up, Harry.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_13.mp3', '[Professor Flitwick] Splendid!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_14.mp3', 'Wingard Leviosa.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_15.mp3', 'Well done, dear.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_16.mp3', 'Ooh.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_17.mp3', 'I think we\'re going to need');
INSERT INTO fragments (filename, tekst) VALUES ('frag_18.mp3', 'another feather over here, professor.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_19.mp3', 'Ah.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_20.mp3', 'Bertie Bott\'s Every-Flavour Beans.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_21.mp3', 'I was most unfortunate in my youth');
INSERT INTO fragments (filename, tekst) VALUES ('frag_22.mp3', 'to come across a vomit-flavoured one.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_23.mp3', 'And since then, I\'m afraid');
INSERT INTO fragments (filename, tekst) VALUES ('frag_24.mp3', 'I\'ve lost my liking for them.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_25.mp3', 'But I think');
INSERT INTO fragments (filename, tekst) VALUES ('frag_26.mp3', 'I could be safe');
INSERT INTO fragments (filename, tekst) VALUES ('frag_27.mp3', 'with a nice toffee.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_28.mp3', 'Hmm.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_29.mp3', 'Alas.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_30.mp3', 'Earwax.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_31.mp3', 'When did he get here?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_32.mp3', 'This morning.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_33.mp3', 'Your sons flew that enchanted car of yours');
INSERT INTO fragments (filename, tekst) VALUES ('frag_34.mp3', 'to Surrey and back last night.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_35.mp3', 'Did you really?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_36.mp3', 'How\'d it go?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_37.mp3', 'I mean,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_38.mp3', 'that was very wrong indeed, boys.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_39.mp3', 'Very wrong of you.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_40.mp3', 'Now, Harry,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_41.mp3', 'you must know all about Muggles.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_42.mp3', 'Tell me,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_43.mp3', 'what exactly is the function of a rubber duck?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_44.mp3', 'You grasp');
INSERT INTO fragments (filename, tekst) VALUES ('frag_45.mp3', 'your Mandrake firmly.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_46.mp3', 'You pull it sharply up, out of the pot.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_47.mp3', 'Got it?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_48.mp3', 'And now');
INSERT INTO fragments (filename, tekst) VALUES ('frag_49.mp3', 'you dump it down into the other pot');
INSERT INTO fragments (filename, tekst) VALUES ('frag_50.mp3', 'and pour a little sprinkling of soil');
INSERT INTO fragments (filename, tekst) VALUES ('frag_51.mp3', 'to keep him warm.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_52.mp3', 'Longbottom\'s been neglecting his earmuffs.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_53.mp3', 'No, ma\'am.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_54.mp3', 'He\'s just fainted.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_55.mp3', 'Brackium');
INSERT INTO fragments (filename, tekst) VALUES ('frag_56.mp3', 'Emendo!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_57.mp3', 'Ah, yes.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_58.mp3', 'Well, that can sometimes happen.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_59.mp3', 'Um...');
INSERT INTO fragments (filename, tekst) VALUES ('frag_60.mp3', 'But, uh, the point is, uh...');
INSERT INTO fragments (filename, tekst) VALUES ('frag_61.mp3', 'you can no longer feel any pain.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_62.mp3', 'And, very clearly, the bones are not broken.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_63.mp3', 'Broken?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_64.mp3', 'There\'s no bones left!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_65.mp3', '[Lockhart] Much more flexible though.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_66.mp3', 'Ron!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_67.mp3', 'Ron, are you okay?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_68.mp3', 'I\'m fine.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_69.mp3', 'Hello.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_70.mp3', 'Who are you?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_71.mp3', 'Um...');
INSERT INTO fragments (filename, tekst) VALUES ('frag_72.mp3', 'Ron Weasley.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_73.mp3', 'Really?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_74.mp3', 'And, uh,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_75.mp3', 'who— Who am I?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_76.mp3', 'Lockhart\'s Memory Charm backfired.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_77.mp3', 'He hasn\'t got a clue who he is.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_78.mp3', 'It\'s an odd sort of place this, isn\'t it?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_79.mp3', 'Do you live here?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_80.mp3', 'No.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_81.mp3', 'Really? Bu—');
INSERT INTO fragments (filename, tekst) VALUES ('frag_82.mp3', 'Housekeeping.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_83.mp3', 'I\'ll come back later.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_84.mp3', 'Don\'t be such a wimp, Longbottom.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_85.mp3', 'I\'m okay.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_86.mp3', 'Okay.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_87.mp3', 'Wand at the ready.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_88.mp3', 'One,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_89.mp3', 'two,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_90.mp3', 'three.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_91.mp3', 'Think, Neville. Think.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_92.mp3', 'Riddikulus!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_93.mp3', 'Wonderful, Neville. Wonderful.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_94.mp3', '[Hagrid] No!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_95.mp3', 'Buckbeak!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_96.mp3', 'Whoa!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_97.mp3', 'Whoa, whoa!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_98.mp3', 'Whoa.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_99.mp3', 'Buckbeak!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_100.mp3', 'Away, yer silly creature.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_101.mp3', 'Ah, it\'s killed me.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_102.mp3', 'It\'s killed me.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_103.mp3', 'Calm down. It— It\'s just a scratch.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_104.mp3', 'Hagrid!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_105.mp3', 'He has to be taken to the hospital.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_106.mp3', 'I\'m the teacher. I\'ll do it.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_107.mp3', '[Draco] Oh, you\'re gonna regret this.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_108.mp3', 'Class dismissed.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_109.mp3', '[Draco] You and your bloody chicken.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_110.mp3', '[Ron] Spiders!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_111.mp3', 'Spiders.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_112.mp3', 'Spiders, they want me to tap dance.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_113.mp3', 'I don\'t wanna tap dance.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_114.mp3', 'You tell those spiders, Ron.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_115.mp3', 'Oh yeah. Tell... Tell them.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_116.mp3', 'I\'ll tell them.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_117.mp3', 'I\'ll tell them.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_118.mp3', 'This castle will not only be your home this year,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_119.mp3', 'but home to some very special guests as well.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_120.mp3', 'You see, Hogwarts has been chosen...');
INSERT INTO fragments (filename, tekst) VALUES ('frag_121.mp3', 'My horses have travelled a long way.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_122.mp3', 'They will need attending to.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_123.mp3', 'Not to worry, Madame Maxime.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_124.mp3', 'Our gamekeeper, Hagrid');
INSERT INTO fragments (filename, tekst) VALUES ('frag_125.mp3', 'is more than capable of seeing to them.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_126.mp3', 'But you know, Monsieur Hagrid,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_127.mp3', 'they drink only single-malt whisky.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_128.mp3', 'You idiot!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_129.mp3', 'Next!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_130.mp3', 'Ready?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_131.mp3', 'Yes!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_132.mp3', 'You said!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_133.mp3', 'You said!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_134.mp3', 'Ah!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_135.mp3', 'All right, you want this?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_136.mp3', 'Get that!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_137.mp3', 'Take that!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_138.mp3', 'Come on then, let\'s do this!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_139.mp3', 'Come on.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_140.mp3', 'Fight, fight, fight, fight, fight!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_141.mp3', 'Cho, Harry\'s looking at you.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_142.mp3', 'Shush!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_143.mp3', '[Hermione] Look at this—');
INSERT INTO fragments (filename, tekst) VALUES ('frag_144.mp3', '[Ron] Dress.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_145.mp3', 'Well, it does match your eyes.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_146.mp3', 'Is there a bonnet?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_147.mp3', 'Aha!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_148.mp3', 'Nose down, Harry.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_149.mp3', 'Ginny, these must be for you.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_150.mp3', 'I\'m not wearing that.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_151.mp3', 'It\'s ghastly.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_152.mp3', 'What you on about?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_153.mp3', 'They\'re not for Ginny.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_154.mp3', 'They\'re for you.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_155.mp3', 'Dress robes.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_156.mp3', '\"Dress robes?\"');
INSERT INTO fragments (filename, tekst) VALUES ('frag_157.mp3', 'For what?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_158.mp3', 'What are those?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_159.mp3', 'No, those?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_160.mp3', 'My dress robes.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_161.mp3', 'Well, they\'re all right.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_162.mp3', 'No lace, no dodgy little collar.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_163.mp3', 'Well, I expect yours are more traditional.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_164.mp3', 'Traditional?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_165.mp3', 'They\'re ancient!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_166.mp3', 'I look like my great-aunt Tessie.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_167.mp3', '[Arthur] Genius, these Muggles.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_168.mp3', '[Announcer] There are severe delays on the Circle');
INSERT INTO fragments (filename, tekst) VALUES ('frag_169.mp3', 'and Hammersmith & City lines.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_170.mp3', 'All other services are running well.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_171.mp3', 'Ah!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_172.mp3', 'Stupefy!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_173.mp3', 'Thank you.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_174.mp3', 'Shut up.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_175.mp3', '[Umbridge] You applied first');
INSERT INTO fragments (filename, tekst) VALUES ('frag_176.mp3', 'for the Defence Against the Dark Arts post.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_177.mp3', 'Is that correct?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_178.mp3', 'Yes.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_179.mp3', 'But you were unsuccessful?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_180.mp3', 'Obviously.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_181.mp3', 'Obviously, she\'s feeling sad about Cedric');
INSERT INTO fragments (filename, tekst) VALUES ('frag_182.mp3', 'and therefore confused about liking Harry');
INSERT INTO fragments (filename, tekst) VALUES ('frag_183.mp3', 'and guilty about kissing him,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_184.mp3', 'conflicted because Umbridge is');
INSERT INTO fragments (filename, tekst) VALUES ('frag_185.mp3', 'threatening to sack her mum');
INSERT INTO fragments (filename, tekst) VALUES ('frag_186.mp3', 'from her job at the Ministry,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_187.mp3', 'and frightened of failing her O.W.L.s');
INSERT INTO fragments (filename, tekst) VALUES ('frag_188.mp3', 'because she\'s so busy worrying about everything else.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_189.mp3', 'One person couldn\'t feel all that.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_190.mp3', 'They\'d explode.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_191.mp3', 'Just because you\'ve got the emotional range of a teaspoon.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_192.mp3', '[Ron] So, what is it he sees in her?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_193.mp3', 'I don\'t know.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_194.mp3', 'She\'s smart, funny...');
INSERT INTO fragments (filename, tekst) VALUES ('frag_195.mp3', 'attractive.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_196.mp3', 'Attractive?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_197.mp3', 'You know, she\'s got nice skin.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_198.mp3', '\"Skin?\"');
INSERT INTO fragments (filename, tekst) VALUES ('frag_199.mp3', 'You\'re saying Dean\'s dating my sister');
INSERT INTO fragments (filename, tekst) VALUES ('frag_200.mp3', 'because of her skin?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_201.mp3', '[Hermione] That\'s Romilda Vane.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_202.mp3', 'Apparently, she\'s trying to smuggle you a love potion.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_203.mp3', 'Really?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_204.mp3', 'Hey!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_205.mp3', 'She\'s only interested in you');
INSERT INTO fragments (filename, tekst) VALUES ('frag_206.mp3', 'because she thinks you\'re the Chosen One.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_207.mp3', 'But I am the Chosen One.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_208.mp3', 'Okay. Sorry. Um...');
INSERT INTO fragments (filename, tekst) VALUES ('frag_209.mp3', 'Kidding.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_210.mp3', 'I can\'t stop thinking about her, Harry.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_211.mp3', 'Honestly, you know, I reckoned she was starting to annoy you.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_212.mp3', 'She could never annoy me.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_213.mp3', 'I think I love her.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_214.mp3', 'We have a plan.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_215.mp3', 'I know, but I\'ve got a really good feeling about Hagrid\'s.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_216.mp3', 'I feel it\'s—');
INSERT INTO fragments (filename, tekst) VALUES ('frag_217.mp3', 'It\'s the place to be tonight.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_218.mp3', 'Do you know what I mean?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_219.mp3', '[Both] No.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_220.mp3', '[Harry] Well, trust me.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_221.mp3', 'I know what I\'m doing. Or Felix does.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_222.mp3', 'Hi!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_223.mp3', 'For those of you who haven\'t taken Polyjuice Potion before,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_224.mp3', 'fair warning, it tastes like goblin piss.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_225.mp3', 'Have lots of experiences with that, do you, Mad-Eye?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_226.mp3', 'Just trying to defuse the tension.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_227.mp3', 'Ah.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_228.mp3', 'Ugh.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_229.mp3', 'This one was definitely part troll, the smell of him.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_230.mp3', 'Engorgio.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_231.mp3', 'Reducio!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_232.mp3', '[Hermione] What\'s going on in there?');
INSERT INTO fragments (filename, tekst) VALUES ('frag_233.mp3', '[Both] Nothing.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_234.mp3', 'Six months she hasn\'t seen me');
INSERT INTO fragments (filename, tekst) VALUES ('frag_235.mp3', 'and it\'s like I\'m Frankie First Year.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_236.mp3', 'I\'m only her brother.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_237.mp3', '[Seamus] She got lots of those though.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_238.mp3', 'She\'s only one Harry.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_239.mp3', 'Shut up, Seamus.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_240.mp3', 'Piertotum Locomotor.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_241.mp3', 'Hogwarts is threatened.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_242.mp3', 'Man the boundaries. Protect us.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_243.mp3', 'Do your duty to our school!');
INSERT INTO fragments (filename, tekst) VALUES ('frag_244.mp3', 'I\'ve always wanted to use that spell.');
INSERT INTO fragments (filename, tekst) VALUES ('frag_245.mp3', 'Heh,');
INSERT INTO fragments (filename, tekst) VALUES ('frag_246.mp3', 'heh, heh.');
